from enum import Enum

class StageOutcome(Enum):
    NO_BANNER = "NO_BANNER"
    UNSUCCESSFUL_INTERACTION = "UNSUCCESSFUL_INTERACTION"
    DIRECT_ACCEPT = "DIRECT_ACCEPT"
    DIRECT_DECLINE = "DIRECT_DECLINE"
    SETTINGS_DECLINE = "SETTINGS_DECLINE"
    SETTINGS_SAVE = "SETTINGS_SAVE"
