from enum import Enum

class VisitStage(Enum):
    NORMAL_INITIAL_VISIT = "NORMAL_INITIAL_VISIT"
    NORMAL_AFTER_TRAVERSIAL = "NORMAL_AFTER_TRAVERSIAL"
    ACCEPT_INITIAL_VISIT = "ACCEPT_INITIAL_VISIT"
    ACCEPT_AFTER_ACTION = "ACCEPT_AFTER_ACTION"
    ACCEPT_AFTER_TRAVERSIAL = "ACCEPT_AFTER_TRAVERSIAL"
    DECLINE_INITIAL_VISIT = "DECLINE_INITIAL_VISIT"
    DECLINE_AFTER_ACTION = "DECLINE_AFTER_ACTION"
    DECLINE_AFTER_TRAVERSIAL = "DECLINE_AFTER_TRAVERSIAL"
