from enum import Enum

class VisitStage(Enum):
    NORMAL_INITIAL_VISIT = "NORMAL_INITIAL_VISIT"
    NORMAL_AFTER_TRAVERSAL = "NORMAL_AFTER_TRAVERSAL"
    ACCEPT_INITIAL_VISIT = "ACCEPT_INITIAL_VISIT"
    ACCEPT_AFTER_ACTION = "ACCEPT_AFTER_ACTION"
    ACCEPT_AFTER_TRAVERSAL = "ACCEPT_AFTER_TRAVERSAL"
    DECLINE_INITIAL_VISIT = "DECLINE_INITIAL_VISIT"
    DECLINE_AFTER_ACTION = "DECLINE_AFTER_ACTION"
    DECLINE_AFTER_TRAVERSAL = "DECLINE_AFTER_TRAVERSAL"
