from enum import Enum

class CookieCategory(Enum):
    STRICTLY_NECESSARY = "STRICTLY_NECESSARY"
    PERFORMANCE = "PERFORMANCE"
    FUNCITONALITY = "FUNCITONALITY"
    TARGETING = "TARGETING"
    UNKNOWN = "UNKNOWN"
